name: Closing Jira
on:
  pull_request:
    types: [closed]
jobs:
  test-create-issue:
    name: Search Issue
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: https://rakshitmohan99.atlassian.net
        JIRA_USER_EMAIL: rakshitmohan99@gmail.com
        JIRA_API_TOKEN: ${{ secrets.JIRA }}
    - name: Auto Comment
      uses: wow-actions/auto-comment@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        pullRequestClosed: >
          👋 @{{ author }} I closed the pull request


 
