name: seach Jira
on:
  pull_request:
    types: [closed]
jobs:
  test-create-issue:
    name: Search Issue
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: https://rakshitmohan99.atlassian.net
        JIRA_USER_EMAIL: rakshitmohan99@gmail.com
        JIRA_API_TOKEN: ${{ secrets.JIRA }}

    - name: Search
      id: search
      uses: tomhjp/gh-action-jira-search@v0.1.0
      with:
        jql: 'key = TEST-23'

    - name: Log
      run: echo "Found issue ${{ steps.search.outputs.issue }}"
