name: Closing Jira
on:
  pull_request:
    types: [closed]
jobs:
  test-create-issue:
    name: Search Issue
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: https://rakshitmohan99.atlassian.net
        JIRA_USER_EMAIL: rakshitmohan99@gmail.com
        JIRA_API_TOKEN: ${{ secrets.JIRA }}

    - name: Search
      id: search
      uses: tomhjp/gh-action-jira-search@v0.1.0
      with:
        jql: 'text ~ "https://github.com/${{ github.repository }}/pull/${{github.event.number}}" order by created DESC'
    - name: Comment on issue
      uses: atlassian/gajira-comment@master
      with:
       issue: ${{ steps.search.outputs.issue }}
       comment: Accepted by POD leaders

    - name: Log
      run: echo "Found issue ${{ steps.search.outputs.issue }}"
    

    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.search.outputs.issue }}
        transition: "Done"
 
