name: tfsec-pr-commenter
on: [pull_request]
jobs:
 tfsec_commenter:
   name: tfsec PR commenter
   runs-on: ubuntu-latest

   steps:
     - name: Clone repo
       uses: actions/checkout@master

     - name: tfsec commenter
       uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
